sonar.projectKey=iot-equipment-loan
sonar.projectName=IoT Equipment Loan System
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.sources=src,public
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
sonar.exclusions=public/iot-equipment.apk,public/icons/**,**/*.bak,node_modules/**,mobile_flutter/**
sonar.javascript.node.maxspace=2048